print('hello world')
print('cual es tu nombre')
myName = input()
print('bienvenido ' +myName)
print('el largo de tu nombre es: ')
print(len(myName))
print('cual es tu edad?')
myAge = input()
print('tu edad sera ' +str(int(myAge) +1) + ' en un anio')
